apiVersion: v1
kind: Service
metadata:
  name: latency-app
  namespace: prod
  labels:
    app: latency-app
spec:
  selector:
    app: latency-app
  ports:
  - name: http
    port: 80
    targetPort: 9898