apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: latency-app-monitor
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: latency-app
  namespaceSelector:
    matchNames:
    - prod
  endpoints:
  - port: http
    path: /metrics
    interval: 10s